plugins {
    id 'fabric-loom' version '1.7.4'
    id 'maven-publish'
}

group = 'com.agustinbenitez.voxelview3d'
version = project.mod_version

base {
    archivesName = project.archives_base_name
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
}

loom {
    runs {
        client {
            client()
            name = 'Fabric Client'
            runDir = 'run'
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

tasks.named('processResources', ProcessResources).configure {
    inputs.property 'version', project.version
    inputs.property 'minecraft_version', project.minecraft_version
    inputs.property 'loader_version', project.loader_version

    filesMatching('fabric.mod.json') {
        expand(
                version: project.version,
                minecraft_version: project.minecraft_version,
                loader_version: project.loader_version
        )
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

tasks.named('jar', Jar).configure {
    from('LICENSE') {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
}

publishing {
    publications {
        create('mavenJava', MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }
}
