plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

group = 'com.example.voxelview3d'
version = '1.0.0'

base {
    archivesName = 'map-3d-usseewa'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

minecraft {
    mappings channel: 'official', version: '1.20.1'

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
        }

        client {
            property 'forge.enabledGameTestNamespaces', 'voxelview3d'
        }

        server {
            property 'forge.enabledGameTestNamespaces', 'voxelview3d'
            args '--nogui'
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.2.0'
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version: '1.20.1',
            minecraft_version_range: '[1.20.1,1.21)',
            forge_version: '47.2.0',
            forge_version_range: '[47,)',
            loader_version_range: '[47,)',
            mod_id: 'voxelview3d',
            mod_name: 'Map 3d usseewa',
            mod_license: 'All Rights Reserved',
            mod_version: '1.0.0',
            mod_authors: 'Agustin Benitez',
            mod_description: 'Client-side 3D map renderer'
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                "Specification-Title"     : "voxelview3d",
                "Specification-Vendor"    : "voxelview3dsareus",
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : "voxelview3dsareus",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
