org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
net.neoforged.gradle.merge-source-sets=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.214
neo_version_range=[21.1.214,)
loader_version_range=[1,)

mod_id=voxelview3d
mod_name=Map 3d usseewa
mod_license=All Rights Reserved
mod_version=1.21.1-1.0.0
mod_group_id=com.agustinbenitez.voxelview3d
mod_authors=Agustin Benitez
mod_description=Client-side 3D map renderer
